### ISSUE TITLE
bsdconf.d examples incorrect

### ISSUE THREAD

**Issue by kewball** [olevole/cbsd-wwwdoc#13]
I do not understand the code in bsdconf.d/pw :(

https://www.bsdstore.ru/en/11.0/modules/bsdconf.d_ssi.html

Example 2:  `sysrc: unknown variable 'service'`

Example 4 & 5: substitute "pw" for "pkg" (my jail name is worker, it has a user name worker)
```sh
    [root@swing ~]# cbsd pw jname=worker user=worker
    pw: unknown keyword `user=worker'
    [root@swing ~]# cbsd pw jname=worker
    Empty command
```

**Comment by olevole** [comment]
Thanks! This is typo in doc:

It should be written as:

% cbsd  passwd

Example5: Change password for web user in jail1:

% cbsd passwd user=web jname=jail1
